# Generated by Django 4.1 on 2022-09-12 09:43

import django.db.models.deletion
from django.db import migrations, models

import drivers.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_alter_account_user_alter_account_uuid'),
        ('drivers', '0003_driverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_docs',
                                    to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='file',
            field=models.FileField(upload_to=drivers.models.driver_directory_path),
        ),
    ]
