# Generated by Django 4.1 on 2022-10-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverdocument_company_alter_driverdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='drivers.driver'),
        ),
    ]
