# Generated by Django 4.1 on 2022-08-16 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
